# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:r)
trigger:
  - main
pr:
  - main

variables:
  GO_VERSION: 1.13
  GOPATH: $(Agent.BuildDirectory)/go

jobs:
  - job: UnitTest
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
    - template: azp-dependencies.yml
    - checkout: self
    - script: make all
      displayName: Run checks and unit test
